freecam:
  enabled: true
  kick-message: "<red>Freecam is not allowed</red>"

messages:
  actor-name: "itzglecni"

pvp:
  enabled-message: "<red>PvP is enabled</red>"
  disabled-message: "<green>PvP is disabled</green>"

holyfreeze:
  enabled-message: "<red><actor> freezed all the players</red>"
  disabled-message: "<green><actor> unfreezed all the players</green>"
